version: '3'

services: 

  wppconnect-server-3:
    build:
      context: ./wppconnect-server-3
      dockerfile: Dockerfile
    restart: always
    image: wppconnect-server-3
    container_name: wppconnect-server-3
    hostname: wppconnect-server-3
    entrypoint: docker-entrypoint.sh yarn dev
    ports:
      - "8082:21467"
    networks:
      - wpp-network
    tty: true
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M

networks: 
  wpp-network:
    name: wpp-network
    driver: bridge 
