version: '3'

services: 

  wppconnect-server-8:
    build:
      context: ./wppconnect-server-8
      dockerfile: Dockerfile
    restart: always
    image: wppconnect-server-8
    container_name: wppconnect-server-8
    hostname: wppconnect-server-8
    entrypoint: docker-entrypoint.sh yarn dev
    ports:
      - "8088:21478"
    networks:
      - wpp-network
    tty: true
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M

networks: 
  wpp-network:
    name: wpp-network
    driver: bridge 
