version: '3'

services: 

  wppconnect-server-9:
    build:
      context: ./wppconnect-server-9
      dockerfile: Dockerfile
    restart: always
    image: wppconnect-server-9
    container_name: wppconnect-server-9
    hostname: wppconnect-server-9
    entrypoint: docker-entrypoint.sh yarn dev
    ports:
      - "8089:21479"
    networks:
      - wpp-network
    tty: true
    deploy:
      resources:
        limits:
          memory: 1000M
        reservations:
          memory: 200M

networks: 
  wpp-network:
    name: wpp-network
    driver: bridge 
