version: '3.8'

services:
  postgres:
    image: postgres
    restart: on-failure:3
    container_name: postgres
    environment:
      POSTGRES_DB: dbpostsql
      POSTGRES_USER: wppconnect
      POSTGRES_PASSWORD: wppsconnect
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - wpp-network

  redis:
    image: redis
    restart: on-failure:3
    container_name: redis
    command: ["redis-server", "--requirepass", "wpprconnect"]
    environment:
      REDIS_PASSWORD: wpprconnect
    volumes:
      - redis_data:/data
    networks:
      - wpp-network

  wppconnect-server-hml:
    build:
      context: ./wppconnect-server-hml
      dockerfile: Dockerfile
    restart: always
    image: wppconnect-server-hml
    container_name: wppconnect-server-hml
    hostname: wppconnect-server-hml
    entrypoint: docker-entrypoint.sh yarn dev
    environment:
      - SECRET_KEY_SERVER=Ec0nnectHML
      - PORT=21483
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=dbpostsql
      - POSTGRES_USER=wppconnect
      - POSTGRES_PASSWORD=wppsconnect
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=wpprconnect
    ports:
      - "8093:21483"
    networks:
      - wpp-network
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    tty: true
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M

networks:
  wpp-network:
    name: wpp-network
    driver: bridge

volumes:
  postgres_data:
  redis_data: